# Generated by Django 4.2.7 on 2025-01-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcereport',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Реальный обьем'),
        ),
    ]
